version: "2"

linters:
  default: all
  disable:
    - depguard
    - dogsled
    - exhaustruct
    - godot
    - noinlineerr
    - nolintlint
    - wrapcheck
    - wsl # deprecated

  settings:
    cyclop:
      max-complexity: 15
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
    varnamelen:
      ignore-names:
        - tt
        - ok
        - tx
        - id
        - db
        - to
        - i

  exclusions:
    rules:
      - path: cmd/
        linters:
          - gochecknoglobals
          - gochecknoinits
          - mnd
      - path: kube/
        linters:
          - gochecknoglobals
          - gochecknoinits

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/logica0419/vault-provisioner)
        - blank
