linters:
  enable-all: true
  disable:
    - tenv # deprecated
    - depguard
    - dogsled
    - gci
    - godot
    - nolintlint
    - exhaustruct
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - path: cmd/
      linters:
        - mnd
        - gochecknoglobals
        - gochecknoinits
    - path: kube/
      linters:
        - gochecknoglobals
        - gochecknoinits

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
  stylecheck:
    checks:
      - all
      - -ST1000
  varnamelen:
    ignore-names:
      - tt
      - tx
      - id
      - db
      - to
      - i
