apiVersion: batch/v1
kind: Job
metadata:
  name: vault-provisioner
spec:
  template:
    spec:
      serviceAccountName: vault-provisioner
      containers:
        - name: vault-provisioner
          image: vault-provisioner:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-provisioner
subjects:
  - kind: ServiceAccount
    name: vault-provisioner
roleRef:
  kind: Role
  name: vault-provisioner
  apiGroup: rbac.authorization.k8s.io
